config/routes.rb
CustoBlocks::Application.routes.draw do
  resources :blocks

  root :to => 'blocks#index'
end

app/models/block.rb
class Block < ActiveRecord::Base
  attr_accessible :block_type, :title
  validates :title, presence: true
  validates :block_type, presence: true

  RESERVED_FIELDS = [ :title, :block_type, :extensions ]
  attr_accessible *RESERVED_FIELDS

  store :extensions

  # determine possible block types by reading config files
  cattr_accessor :block_types

  @@block_types = {}

  def self.add_block_type key, block_data
    @@block_types[key] = HashWithIndifferentAccess.new(block_data)
    @@block_types[key].each do |k,v|
      unless RESERVED_FIELDS.include? k.to_sym
        store_accessor :extensions, k.to_sym
      end
    end
  end

  # initialize
  Dir.glob(File.join(Rails.root, 'config', 'blocks','*_block.yml')).each do |f|
    puts "Reading #{f}"
    begin
      key = File.basename(f).gsub(/\.yml$/,'').classify
      add_block_type key, YAML.load(File.open(f))
   rescue Exception => ex
      puts ex
      Rails.logger.warn "Failed to import block #{f}"
      Rails.logger.warn ex
    end
  end  

  def template_name 
    self.block_type.tableize.singularize
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  # Uncomment to require auth on all actions (and opt-out when necessary).
  #before_filter :require_login, except: [:not_authenticated]

  protect_from_forgery

end

app/controllers/blocks_controller.rb
class BlocksController < ApplicationController
 
  before_filter :type_is_required, :only => [:new]

  def index
    @blocks = Block.all
    @blocks_by_type = @blocks.inject({}) {|result,item| (result[item.block_type] ||= []) << item; result}
  end

  def show
    @block = Block.find(params[:id])
  end

  def new
    @block = Block.new(block_type: params[:type])
  end

  def edit
    @block = Block.find(params[:id])
  end

  def create
    @block = Block.new(params[:block], :without_protection => true)

    if @block.save
      redirect_to @block, notice: 'Block was successfully created.'
    else
      render action: "new"
    end
  end

  def update
    @block = Block.find(params[:id])
    if @block.update_attributes(params[:block], :without_protection => true)
      redirect_to @block, notice: 'Block was successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    @block = Block.find(params[:id])
    @block.destroy
    redirect_to blocks_url
  end

  protected
  def type_is_required
    message = "You must specify a block type."
    redirect_to(blocks_path, :flash => {:error => message}) unless params[:type]
  end

end

app/helpers/admin_form_builder.rb
# in app/helpers/admin_form_builder.rb
class AdminFormBuilder < ActionView::Helpers::FormBuilder
  
  ####
  # To control classes on fields, pass in the following in your options hash
  #   :row_class => 'whatever'  : this will add a class 'whatever' to the field wrapper (which is a row)
  #   :input_html => {:class => 'whatever'}  : this will add all these elements to the input/textarea tag as attributes
  #                                           Note: if you use the field_row method, this will be ignored
  #
  def file_input_row(field, hint = '', opts = {})
    exists_method = "#{field}?"
    # wrap input in div.span5 for file only
    if object.respond_to?(exists_method) && object.send(exists_method)
      opts[:help] = ["Current Image: #{File.basename(object.send(field).to_s)}", opts[:help].to_s].join('<br>').html_safe
      opts[:icon] = object.send(field).url(:icon)
    end
    input_field = @template.content_tag(:div, self.send(:file_field, field, opts[:input_html] || {}), :class => 'span5')
    field_row(field, input_field, hint, opts)
  end
  
  def text_input_row(field, hint = '', opts = {})
    input_field_row field, :text_field, hint, opts
  end
  
  def textarea_input_row(field, hint = '', opts = {})
    input_field_row field, :text_area, hint, opts
  end

  def select_input_row(field, hint = '', opts = {})
    # select_opts looks like [ [display1, value1], [display2, value2]...]
    field_row field, select(field, opts.delete(:select)), hint, opts
  end
      
  def date_input_row(field, hint = '', opts = {})
    input_field_row field, :date_select, hint, opts.merge({:input_field_wrapper_class => 'date'})
  end

  def input_field_row(field, input_field_helper, hint, opts = {})
    input_field = self.send(input_field_helper, field, opts[:input_html] || {})
    field_row(field, input_field, hint, opts)
  end
  
  # use this only when you have some custom input content that needs to be built outside of these
  # functions.  For example, a select button might be constructed like this
  #
  #   field_row form, :my_field, form.select(:my_field, MyModel.select_options.map{|m| [m.name, m.id]}), 'Select a value for field.'
  #
  
  def field_row(field, input_area_content, hint, opts = {})
    begin
      p "Object", object
      if object.class == Block 
        block_info = Block.block_types[object.block_type]
        if block_info && block_info[:exclude]
          return '' if block_info[:exclude].include? field.to_s
        end
      end
    rescue
    end

    required_fields = object.class.validators.select{|c| /Presence/.match(c.class.to_s)}.map(&:attributes).flatten
    row_classes = ["field_#{field}", opts[:row_class].to_s]
    row_classes << 'required' if required_fields.include? field
    row_class = row_classes.uniq.join ' '
    input_field_wrapper_class = ['controls','span6', opts[:input_field_wrapper_class].to_s].join ' '

    @template.content_tag 'div', :class => "control-group row #{row_class}" do 
      
      # put label block and input field block together in the wrapper row and return it
      (@template.content_tag :div, :class => 'span2' do
         self.label(field, :class => 'control-label') +
           @template.content_tag(:p, hint, :class => 'caption')
       end) + 
        (@template.content_tag(:div, :class => input_field_wrapper_class) do
           help_chunk = ''
           img_chunk = ''
           if opts[:icon] && !opts[:icon].empty?
             img_chunk = @template.content_tag(:div, @template.tag(:img, :src => opts[:icon]), :class => 'span1')
           end
           if opts[:help] && !opts[:help].empty?
             help_chunk = @template.content_tag(:span, opts[:help], :class => 'span6 help-block')
           end
           img_chunk.html_safe + input_area_content.html_safe + help_chunk.html_safe
         end)
    end
  end
end

app/helpers/admin_helper.rb
# in app/helpers/admin_helper.rb
module AdminHelper

  def admin_form_for(name, *args, &block)
    options = args.extract_options!
    form_for name, *(args << options.merge(:builder => AdminFormBuilder)), &block
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def alert_class(alert_type)
    alert_type = {
      alert: 'error',
      notice: 'info'
    }.fetch(alert_type, alert_type.to_s)
    "alert-#{alert_type}"
  end

end

app/helpers/blocks_helper.rb
module BlocksHelper
  def render_dynamic_form_fields(form, block, opts={})
    s = ''
    begin
      (Block.block_types[block.block_type] || {}).each do |k,v| 
        opts.merge!({as: v[:datatype], label: v[:display_name]})
        s += form.send('input', k, opts)
      end
      s.html_safe
    rescue Exception => ex
      Rails.logger.warn 'Failed to add form fields for block [%s]' % block.inspect
      Rails.logger.warn 'Check the YAML file for that block and make sure it\'s properly configured'
      Rails.logger.warn ex
      ''
    end
  end

  def render_config_file(block)
    fname = File.join(Rails.root, 'config','blocks', "#{block.template_name}.yml")
    File.open(fname).read if File.exists? fname
  end
      
end

app/views/blocks/_form.html.slim
= simple_form_for(@block, :html => {:class => 'form-horizontal' }) do |f|

  .form-inputs
    = f.hidden_field :block_type
    = f.input :title, placeholder: 'Insert a title'
    = render_dynamic_form_fields(f, @block)


  .form-actions
    = f.button :submit, class: 'btn btn-primary'
    '
    = link_to 'Back', blocks_path, class: 'btn'

app/views/blocks/_rock_block.slim
.rock_block
  h1= @block.title
  .rock_field
    = "#{@block.rock} is a kind of rock"
  .roll_field
    = "#{@block.roll} is a kind of roll"

app/views/blocks/_super_block.slim
dl
  dt Title
  dd= @block.title
  dt My alias name is
  dd= @block.alias
  dt And my super power is 
  dd= @block.super_power

app/views/blocks/edit.html.slim
.page-header
  h1 Editing #{@block.block_type}

== render 'form'

app/views/blocks/index.html.slim
- Block.block_types.each do |type, block_def|
  .span12
    h2= type.tableize.humanize.titleize
    = link_to "New #{type}", new_block_path(type: type), class: 'btn new_block'
    



  table.table.table-striped
    thead
      tr
        th Title
        th Actions
        
    tbody
    - (@blocks_by_type[type] || []).each do |block|
      tr
        td= link_to(block.title, block)
        td
          = link_to 'Edit', edit_block_path(block), class: 'btn btn-mini'
          = link_to 'Destroy', block_path(block), method: :delete, data: { confirm: "Are you sure?" }, class: 'btn btn-mini btn-danger'
  

app/views/blocks/new.html.slim
.page-header
  h1 Create #{@block.block_type}

== render 'form'

app/views/blocks/show.html.slim
.page-header

.container.row
  .span6
    = render @block.template_name
  .span4
    dt Model Configuration (#{@block.template_name}.yml)
    dd
      pre
        code
          = render_config_file @block
  
      
.container.row
  = link_to 'Edit', edit_block_path(@block), class: 'btn'
  = link_to 'Back', blocks_path, class: 'btn'
  = link_to'Destroy', block_path(@block), method: :delete, data: { confirm: "Are you sure?" }, class: 'btn btn-danger'

app/views/layouts/application.html.slim
doctype 5
html
  head
    title Custo_blocks
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tag

  body id=(controller.controller_name) class=(controller.action_name)
    .wrapper
      .container
        header.navbar.navbar-fixed-top
          nav.navbar-inner
            .container
              a(href="https://github.com/you")
                img style=("z-index:100; position: absolute; top: 0; right: 0; border: 0;") src=("https://s3.amazonaws.com/github/ribbons/forkme_right_darkblue_121621.png") alt=("Fork me on GitHub")
              .brand 
                a href='/blocks' Custo_blocks

        - flash.each do |name, msg|
          = content_tag :div, raw(msg), class: "alert #{alert_class(name)}"

        = yield

      .push

    footer
      .container
        p &copy; 2012 All rights reserved.